import {
  GeistPixelSquare,
  GeistPixelGrid,
  GeistPixelCircle,
  GeistPixelTriangle,
  GeistPixelLine,
} from "geist/font/pixel";

import { GeistSans } from "geist/font/sans";

import "./globals.css";
import LateralBar from "../../components/LateralBar";
import Basebord from "../../components/Basebord";
import Topbord from "../../components/Topbord";
import { notFound } from "next/navigation";
import { languages } from "../../../constants/language";

import { Analytics } from "@vercel/analytics/next";

import GoogleAnalytics from '@/components/GoogleAnalytics';

// IMPORTAÇÕES DO CONTEXTO
import { UIProvider } from "../../context/UIContext";
import { ViewportProvider } from "@/context/ViewportContext";

// IMPORTAÇÕES DO NEXT-INTL
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

export const metadata = {
  title: "Decimatrix",
  description: "Generated by create next app",
};

// ASYNC -> Por causa do getMessages()
export default async function RootLayout({ children, params }) {
  // 1. Aguarda os parâmetros 
  const { locale } = await params;

  // 2. Validação de segurança
  if (!languages.includes(locale)) {
    notFound();
  }

  // 3. Carrega as mensagens (o JSON) do lado do servidor
  const messages = await getMessages({ locale });

  return (
    <html lang={locale} className={GeistSans.variable}>
      <body>
        {/* 4. O PROVIDER É OBRIGATÓRIO!
            Ele pega as mensagens que o servidor carregou e entrega
            para os componentes de cliente.
        */}

        <GoogleAnalytics />

        <NextIntlClientProvider messages={messages}>
            <UIProvider>
              <ViewportProvider>
                <Topbord />
                <div style={{ marginTop: "130px" }}> {/* Dá um espaçamento para o conteúdo não ficar embaixo do topbord, que é fixo */}
                  {children}
                </div>

              
                <LateralBar />
                <Basebord />
              </ViewportProvider>
            </UIProvider>  
            
            <Analytics />
            
        </NextIntlClientProvider>
      </body>
    </html>
  );
}